[versions]

# plugins
shadow = "8.1.1"
blossom = "1.3.1"
spotless = "6.20.0"
nexusPublish = "2.0.0-rc-1"
checkstyleTools = "10.12.2"

# general
gson = "2.10.1"
netty = "4.1.96.Final"
annotations = "24.0.1"

# platform api versions
sponge = "10.0.0"
minestom = "c5047b8037"
paper = "1.20.1-R0.1-SNAPSHOT"

# platform extensions
paperLib = "1.0.8"
protocolLib = "03d7be13d0"
packetEvents = "2.1.0-SNAPSHOT"


[libraries]

# general
netty = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

# platform api
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
sponge = { group = "org.spongepowered", name = "spongeapi", version.ref = "sponge" }
minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }

# platform extensions
paperLib = { group = "io.papermc", name = "paperlib", version.ref = "paperLib" }
protocolLib = { group = "com.github.dmulloy2", name = "ProtocolLib", version.ref = "protocolLib" }
packetEvents = { group = "com.github.retrooper.packetevents", name = "spigot", version.ref = "packetEvents" }

# dummy version, just here for renovate to detect that there is something to update
checkstyleTools = { group = "com.puppycrawl.tools", name = "checkstyle", version.ref = "checkstyleTools" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }
